server:
  port: 9998

spring:
  application:
    name: reative-user-service

  cloud:
    nacos:
      discovery:
        server-addr: 121.199.65.11:8848  # 注册中心地址
#        cluster-name: mall #集群名称
        metadata:
          version: v1.0
    loadbalancer:
      ribbon:
        enabled: false

  r2dbc:
    url: r2dbc:mysql://121.199.65.11:3306/mall
    username: root
    password: 970210Lsm

